INSERT INTO Equipment (EType, IsSensitive) VALUES
('ULT Freezer', 1),
('Walk-in', 1),
('Hazardous waste', 1),
('Chest Freezer', 1),
('Computer Servers', 1),
('CO2 incubator', 1),
('Refrigerator and/or Freezer', 1),
('Mass Spectrometer', 1),
("NMR's", 1),
('Luminex and other processing equipment', 1),
('Research computer', 1),
('DXA', 1),
('Glove Box', 1),
('instrumenatation and equipment', 1),
('Vacuum pump and laser', 1),
('Live plant collections, live research projects', 1),
ON DUPLICATE KEY UPDATE EType=VALUES(EType), IsSensitive=VALUES(IsSensitive);

INSERT INTO Actions (ActionID, ActionDescription) VALUES
(1, 'No action needed if building is secure and there is continual electrical service.'),
(2, 'Authorized staff would need one-time access to safely shut down and stow equipment.'),
(3, 'Authorized staff would need one-time access to move hazardous materials to safe storage.'),
(4, 'Authorized staff would need regular access to monitor and perform upkeep.'),
(5, 'Authorized staff would need perodic access to monitor and perform upkeep.'),
(6, 'Equipment and/or materials would need to be relocated for backup power, containment, monitoring, upkeep.'),
(7, 'Equipment and/or materials cannot be relocated; authorized staff would need regular access to monitor health and perform upkeep.'),
(8, 'Alternative best action');

INSERT INTO People (FullName) VALUES
('John Merriam'),
('Doug Brewster'),
('Mike Jones'),
('Craig Jacobson'),
('Dave Clendenen'),
('Dave Camp'),
('Joyce Lin'),
('Mallary Wacker'),
('Jason Blank'),
('Mike Black'),
('Emily Taylor'),
('Sandy Clement'),
('Larisa Vredevoe'),
('Lauren Chan'),
('Mark Wacker'),
('Heather Liwanag'),
('Jen Yost'),
('Marie Yeung'),
('Pat Fidopiastis'),
('Christy Strand'),
('Elena Keeling'),
('Nikki Adams'),
('Erin Johnson'),
('Kevin Dunham'),
('Jen Vanderkelen'),
('Nathaniel Martinez'),
('Alexis Pasulka'),
('Sean Lema'),
('Lars Tomanek'),
('Andrea Laubscher'),
('Tom Featherstone'),
('Eric Benson'),
('Casey Heany'),
('Cory Greever'),
('Julia Jones'),
('Emily Kelly'),
('Celine DiBernardo'),
('Kevin Thompson'),
('Gage Willey'),
('Matt Ritter');