SUCCESS = "SUCCESS"
ERR_UNAUTHORIZED = "ERR_UNAUTHORIZED"
ERR_DUPLICATE = "ERR_DUPLICATE"
ERR_FK_VIOLATION = "ERR_FK_VIOLATION"
ERR_TYPE_MISMATCH = "ERR_TYPE_MISMATCH"
ERR_LOGGING_FAILURE = "ERR_LOGGING_FAILURE"
ERR_NOT_FOUND = "ERR_NOT_FOUND"

